### ISSUE TITLE
Testing double IEEE754 measures

### ISSUE THREAD

**Issue by NicoloToscani** [NicoloToscani/node-red-contrib-siemens-sentron#2]
Testing 64 bit double measures to check correct IEEE754 format:

- Total active energy import tariff 1
- Total active energy import tariff 2
- Total active energy export tariff 1
- Total active energy export tariff 2
- Total reactive energy import tariff 1
- Total reactive energy import tariff 2
- Total reactive energy export tariff 1
- Total reactive energy export tariff 2
- Total apparent energy tariff 1
- Total apparent energy tariff 2

**Comment by Strunck** [comment]
Hello, 
I could test some values. Althoug I did not have the tariff 2 values. It is only a little test setup an my workbench.
But the reading of the double measures seem to be correct.
![PAC2200](https://user-images.githubusercontent.com/64785859/168837588-c0d6e3f2-a993-49c0-9998-4a91c1c7cdaf.png)

![PAC2200 Node-Red](https://user-images.githubusercontent.com/64785859/168837608-a7bb9681-1795-4265-b55e-3fa17a3b5e45.png)

I used the following flow:

[node-red-flow-Test-double.zip](https://github.com/NicoloToscani/node-red-contrib-siemens-sentron/files/8709178/node-red-flow-Test-double.zip)

**Comment by NicoloToscani** [comment]
Are the other PAC2200 correct ? 
For example: Voltage, Current, Frequency, ......

**Comment by Strunck** [comment]
Hello,

I compared the PAC2200 Webinterface with the output in Node-Red:
Voltage L*-N correct
Voltage L*-L* correct
Current L* correct

The others I did not use yet.
The source code looked ok, since the addresses matched the ones in the documentation.

**Comment by NicoloToscani** [comment]
Good, thanks.
