### ISSUE TITLE
Invalid Properties: DeviceProtection

### ISSUE THREAD

**Issue by Hyperfluff** [NicoloToscani/node-red-contrib-siemens-sentron#23]
When you add a new Measure Node onto the Canvas and select Device "PAC4200", then select Measure Voltage L1-N and deploy it will prompt an error warning that the Node is not configured correctly (see Image below)
![image](https://user-images.githubusercontent.com/37953262/183857846-28c98e10-9c58-4c8a-b9c1-93d45b3669fa.png)
![image](https://user-images.githubusercontent.com/37953262/183858143-23aae336-6ac7-4a1c-810e-cf10a288ac15.png)

This is due to the Parameter "deviceProtection" not being set to anything.
If you then change the Device to Circuit Protection, Select Powercenter 100 & Alarm Status and Deploy you set the Parameter deviceProtection removing the warning
changing the Node back to PAC4200 after setting it to Powercenter once then does not prompt an error.

It Seems that the Parameter deviceProtection needs to be initialized or something to not prompt an error...
maybe that can be resolved.

Used Node-Red Version is 3.0.1
Used Library Version is 0.0.30
if further Information is needed i am happy to supply those
~Hyperfluff

**Comment by NicoloToscani** [comment]
Hi, 

can you test on other devices ?

**Comment by Hyperfluff** [comment]
So i have now tested this on a Windows Machine running Node-Red v2.2.0 and Nodejs V14.17.1
adding a new Measure Node, setting it to PAC4200 and Voltage L1-N gives the same error as on the PI
you can try adding the Flow in your Node-Red by going to the top right, select import and Copy Paste the attatched JSON block below, then we can see if it marks it as invalid on your machine.
(Sorry the JSON file cannot be uploaded so i have to include it as plaintext...)
<details>
  <summary>Show JSON</summary>
[{"id":"0bf2d14e6de677bb","type":"measure","z":"a0b0bd0a7e2e5f9e","name":"","unitId":"1","device":"pac4200","deviceProtection":"","data":"voltage-L1N","x":460,"y":360,"wires":[["20d7aac0c3025191"]]},{"id":"d58a5b016cb5af75","type":"inject","z":"a0b0bd0a7e2e5f9e","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":240,"y":360,"wires":[["0bf2d14e6de677bb"]]},{"id":"20d7aac0c3025191","type":"debug","z":"a0b0bd0a7e2e5f9e","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":690,"y":360,"wires":[]},{"id":"51e43189a7cbab2b","type":"measure","z":"a0b0bd0a7e2e5f9e","name":"","unitId":"1","device":"pac4200","deviceProtection":"powercenter1000","data":"voltage-L1N","x":460,"y":440,"wires":[["bbbac3ae5f62b9e9"]]},{"id":"5cab73c0497f79cc","type":"inject","z":"a0b0bd0a7e2e5f9e","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":240,"y":440,"wires":[["51e43189a7cbab2b"]]},{"id":"bbbac3ae5f62b9e9","type":"debug","z":"a0b0bd0a7e2e5f9e","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":690,"y":440,"wires":[]},{"id":"4eb8857bc1b6fa21","type":"comment","z":"a0b0bd0a7e2e5f9e","name":"Description 1, Open me.","info":"1. Added Measure Node\n2. Set to PAC4200 & Voltage L1-N\n3. Pressed Finish\n4. Deployed, got an Error","x":290,"y":320,"wires":[]},{"id":"773da4c55edcc577","type":"comment","z":"a0b0bd0a7e2e5f9e","name":"Description 2 - Workaround, Open me.","info":"1. Copied above Measure Node\n2. Changed from PAC4200 to Circuit Protection\n3. Selected Powercenter 1000 & Alarm Status\n4. Pressed Finish\n5. Deployed without error\n6. Changed Back from Circuit Protection to PAC4200\n7. Deployed without error","x":330,"y":400,"wires":[]}]
</details>
in the Flow I have added the One version throwing an error and the second node after doing the workaround with setting it to Powercenter 1000 temporarily
![image](https://user-images.githubusercontent.com/37953262/184101891-9f15e766-4ca6-44cb-9e15-ba171cb418c5.png)

**Comment by Hyperfluff** [comment]
![image](https://user-images.githubusercontent.com/37953262/184102017-e060fb80-c44b-4694-bbe1-c8ab2ab3d299.png)
Sorry had to reupload the image because HTML Statements and Markdown dont like each other...

**Comment by NicoloToscani** [comment]
Can you check with node version 0.0.32 ?

**Comment by Hyperfluff** [comment]
Checked, it still has the same behaviour, have you tried my JSON example?

**Comment by NicoloToscani** [comment]
Fixed in 0.0.33 after deviceProtection variable initialization.

Can you check this ?

**Comment by Hyperfluff** [comment]
The Issue has now been resolved, adding a new Measure Node now works without the Error Message, thank you.
